### ISSUE TITLE
Research deployment with AWS/Azure

### ISSUE THREAD

**Issue by abeljoseph** [serosurveillance-can-dev/sero-can-webapp#28]
Research a deployment strategy based on [Option 1](https://drive.google.com/file/d/1a_pkEWd2UL_KqzH1VcOc4gLK51fdnKzT/view).

**Comment by atatmaja** [comment]
@abeljoseph Do you mind also researching whether what we eventually need can be accomplished simply using github pages? Hypothesis is probably not but want to make sure

**Comment by abeljoseph** [comment]
> @abeljoseph Do you mind also researching whether what we eventually need can be accomplished simply using github pages? Hypothesis is probably not but want to make sure

@atatmaja 
Just looked into it, seems as though it's possible to host our React app with GitHub pages, but our backend will need to be hosted elsewhere (i.e. Heroku/AWS/Azure). We could go this route, but I foresee latency being an issue since backend-frontend communication will need to occur over the internet
